### ISSUE TITLE
You can add a ai set?

### ISSUE THREAD

**Issue by Abo233** [Insane96/IguanaTweaksReborn#100]
1.Let some monsters can dig diamonds  
(1).Add a mob list
(2).Add a monster mining block list

2.Configurable monster mining speed

**Comment by Abo233** [comment]
3.Automatic ai pathfinding
Will be looking for a new path

**Comment by Insane96** [comment]
Adding AI is a pretty tough task. As a separate mod would be really cool (something like Epic Siege), but not really into IguanaTweaks
