### ISSUE TITLE
[Weight] An interesting changes

### ISSUE THREAD

**Issue by Abo233** [Insane96/IguanaTweaksReborn#101]
1.Through the right mouse button to add a new articles and use this item, can improve the weight limit

2.Limit the item promotion value（configurable)
      Describe：
      Every time use lifting the weight of the 5 limit, or even more(Configuration by the players 
      themselves)

3.It takes experience to use this item(configurable)
        Describe：For example: consumption level 3 experience can use this item, and more
        (Configuration by the players themselves)

**Comment by Abo233** [comment]
This is a very flexible changes
1. Improve the module compatibility,
2. Reduce the difficulty of late

3.Can be restrictions on the ability of players items use restrictions
    Describe;
    Such as players at the start of the weight limit is 50. Only some items weight is 50, so players 
   can't use, these are all can pass the custom and custom weight weight limit, and the mod 
   compatibility is stronger

**Comment by Insane96** [comment]
I had already a few ideas on how to increase weight late game.

Don't like the idea to have an item that increases infinitely the weight limit. Even if it's locked behind an experience cost.
