### ISSUE TITLE
1.15.2 v2.0.0 Server Crash on Boot

### ISSUE THREAD

**Issue by MindlessPuppetz** [Insane96/IguanaTweaksReborn#104]
Follow the following guideline. Not following this will result in ignored and closed issue.

// Only versions for Minecraft 1.12 and 1.14 are supported

**Minecraft Version**:
1.15.2 (I know this isn't a supported version, just passing the report along so you can work at kinks as you port the mod.)

// Please make sure you're using the latest version before sending a report

Mod Version:
2.0.0

**Forge Version**:
31.1.41

**What Happens**:
Mod works fine on single player, but causes a crash on boot for servers. I am including two reports. One WITH Immersive Portals, and one WITHOUT Immersive Portals. First crash hinted at an issue with Immersive Portals, so tried without but it still crashed.

//Please send logs even if you don't have any crash, and use Pastebin or similar

**Logs / Crash reports (use pastebin.com)**:
w/ Immers Portals: https://pastebin.com/bKsQdUNA
w/out Immers Portals: https://pastebin.com/KCNmG5TV

//If different from default
**Config**:
https://pastebin.com/pdAkxeiX

**List of mods installed / modpack**:
https://www.curseforge.com/minecraft/modpacks/ts-uprising/files/2925620

**Comment by Insane96** [comment]
I'll investigate

**Comment by MindlessPuppetz** [comment]
Server boots up great with this patch, thanks for the quick response/fix!
