### ISSUE TITLE
Incompatibility with Mechanical Crafting (and Mystical Gears in certain cases)

### ISSUE THREAD

**Issue by big-099117109** [Insane96/IguanaTweaksReborn#110]
**Minecraft Version**: 1.12.2
**Mod Version**: 1.4.20
**Forge Version**: 14.23.5.2854

IguanasTweaks calls net.insane96mcp.iguanatweaks.utils.Utils.GetItemWeight when loading the game, crashes for sturdy gearbox, and I assume will for any block which can have "down" as its "facing" property (e.g. the thaumcraft motors in Mystical Gears)

**Logs / Crash reports**: https://pastebin.com/MUTF3g0k

**List of mods installed / modpack**:
IguanaTweaksReborn-1.4.20-mc1.12.x.jar
Mystical Mechanics-0.11.jar
MechanicalCrafting-1.1.1.jar
mystgears-1.0.5.jar
mysticallib-1.12.2-1.4.0.jar

**Comment by Insane96** [comment]
1.12 is no longer supported

**Comment by big-099117109** [comment]
is the source code for 1.12 still around?

**Comment by Insane96** [comment]
Master should still be at 1.12

Il Ven 1 Mag 2020, 20:41 big-099117109 <notifications@github.com> ha
scritto:

**Comment by big-099117109** [comment]
ait thanks

**Comment by Insane96** [comment]
Sadly I never figured out how to fix this problem
