### ISSUE TITLE
Crash with FutureVersions Version 1.3.0.2

### ISSUE THREAD

**Issue by hasuu** [Insane96/IguanaTweaksReborn#113]
Crashes on minecraft 1.12 loading. Only 2 mods.

**Comment by Insane96** [comment]
No crash log and 1.12 is no longer supported. Also no 1.3.0.2 version exists

**Comment by hasuu** [comment]
oh right so just close the issue like there is none. useless neckbeard

**Comment by Insane96** [comment]
Update your game
