### ISSUE TITLE
A conflict with Mowzie's Mobs

### ISSUE THREAD

**Issue by nebelhund** [Insane96/IguanaTweaksReborn#114]
**Minecraft Version**: 1.12.2
**Mod Version**: 1.5.0
**Forge Version**: 14.23.52854

**What Happens**: Game crashes when I use Ice Crystal from Mowzie's Mobs on any mob.

**Logs / Crash reports**: https://pastebin.com/hhaNtvfp

**List of mods installed / modpack**: It's in crash-report

**Comment by Insane96** [comment]
1.12 is no longer supported
