### ISSUE TITLE
custom item weights don't take affect

### ISSUE THREAD

**Issue by Nathan22211** [Insane96/IguanaTweaksReborn#115]
Follow the following guideline. Not following this will result in ignored and closed issue.

// Usually only latest versions are supported

**Minecraft Version**: 1.12.2

// Please make sure you're using the latest version before sending a report

Mod Version: 1.5.0

**Forge Version**: 14.23.5.2854

**What Happens**: might be a visual bug, but the item weight tooltip, and possibly the weights themselves, aren't changed by the custom weights option in the config

//Please send logs even if you don't have any crash, and use Gist or Pastebin

**Logs / Crash reports**: https://gist.github.com/Nathan22211/b23d860998d6e63b83f8eae39723209d

//If different from default
**Config**: since this is only affecting custom weights, might be best to look at that
        S:"Custom Weights" <
            pyrotech:worktable:0:2.0
            pyrotech:rock:0:0.05
            pyrotech:rock:1:0.05
            pyrotech:rock:2:0.05
            pyrotech:rock:3:0.05
            pyrotech:rock:6:0.04
            pyrotech:rock:8:0.005
            pyrotech:rock:4:0.00000000000001
            pyrotech:rock:7:0.00000001
            pyrotech:rock:5:0.000000000000000000001
            pyrotech:rock:9:0.000000000000000000001
            pyrotech:rock_grass:0:0.00000000000001
            pyrotech:crude_axe:0:0.1
            pyrotech:crude_hoe:0:0.1
            pyrotech:crude_pickaxe:0.1
            pyrotech:crude_shovel:0.1
            pyrotech:crude_fishing_rod:0.2
            pyrotech:crude_hammer:0:0.2
            minecraft:stone:0:5.0
         >

**List of mods installed / modpack**: had to extract the manifest for this, just check the entries in the HTML list https://gist.github.com/Nathan22211/0283fa50267bec1c277d476a0517d957

**Comment by Insane96** [comment]
1.12 is no longer supported
