### ISSUE TITLE
More functionality from Hunger Overhaul - passive healing

### ISSUE THREAD

**Issue by phyne** [Insane96/IguanaTweaksReborn#116]
> Health heals while your hunger is above 3 shanks (albeit slower)
> So you don't need to eat as soon as you have lost a couple of shanks
> It seemed pointless to have a food that restored a large amount of hunger when
> you had to stay at max hunger just to heal
> Now you can let your hunger drop to around halfway before eating
> Healing gets progressively slower as your health gets lower

All sorts of configurable options for any hunger related things would be cool as well:
Amount of exhaustion from passive healing, amount/speed of fast healing from saturation when at full hunger (I would generally configure my server without fast healing at all, but for passive healing only), amount of hunger required to begin passive healing, etc. 

Thanks!

**Comment by Insane96** [comment]
The problem with this is that requires AppleCore, a mod that adds an API to manipulate hunger, regen and health. I would have added those pretty much asap. AppleCore will no longer be ported but Parker made a Pull Request in Forge to implement all the APIs from AppleCore directly onto forge.
Sadly we must wait for the PR to be merged: https://github.com/MinecraftForge/MinecraftForge/pull/7266

**Comment by phyne** [comment]
Fair enough, thanks for the info!
