### ISSUE TITLE
[1.16.5] [2.4.2] IguanaTweak server startup crash | com.mojang.blaze3d.matrix.MatrixStack

### ISSUE THREAD

**Issue by Cixon** [Insane96/IguanaTweaksReborn#128]
**Minecraft Version**:
Title.

Mod Version:
Title.

**Forge Version**:
36.0.42

**What Happens**:
The server refuses to load when trying to load IguanaTweaks.

**Logs / Crash reports**:
[latest.log](https://github.com/Insane96/IguanaTweaksReborn/files/6112030/latest.log) **Line 33**
[debug.log](https://github.com/Insane96/IguanaTweaksReborn/files/6112032/debug.log) **Line 1512**

// Config?
_N/A | First Installation._

**List of mods installed / modpack**:
Personal Modpack:
https://drive.google.com/file/d/1mYoFvp9sn-Na_vAiK-SRTlToa7aWBVxW/view?usp=sharing

**Comment by Insane96** [comment]
Fixed in 2.4.3

**Comment by Cixon** [comment]
excellent! thank you!
