### ISSUE TITLE
[1.16.5] Add support for Lightweight enchant via Elenai Dodge 2 mod

### ISSUE THREAD

**Issue by Cixon** [Insane96/IguanaTweaksReborn#129]
// Here your suggestion

**Description:** Elenai Dodge adds a dodge mechanic to minecraft and it's a very stable mod.
It adds a new status bar "feathers" which the more feathers u have, the more u can dodge.
The more armor you put on, the less you can dodge.

**Feature Request:** Elenai Dodge also adds a new enchantment called Lightweight. Lightweight allows users to gain more dodges whilst still wearing heavier armor. I'd love if this enchantment would be adopted to benefit IguanaTweaks armor weight mechanic, a fair way of using it would be -25% less speed reduction per tier per armor piece.

Tier 1 Lightweight // -25% Speed Reduction
Tier 2 Lightweight // -50% Speed Reduction
Tier 3 Lightweight //-75% Speed Reduction

**Mod Link:** https://www.curseforge.com/minecraft/mc-mods/elenai-dodge-2

**Comment by Insane96** [comment]
Does the enchantement work for each piece of armor, or it's just needed on one?

**Comment by Cixon** [comment]
The enchantment does indeed apply to all armor pieces and even modded armor support!

**Comment by Insane96** [comment]
Sorry, I didn't explain myself properly. Does it work on every armor piece
or it's required on only one (like Thorns)?. I'm guessing yes

**Comment by Cixon** [comment]
> 
> Sorry, I didn't explain myself properly. Does it work on every armor piece or it's required on only one (like Thorns)?. I'm guessing yes

It's like protection enchant, u can use it once per armor piece. It also stacks

**Comment by Insane96** [comment]
Thanks for the clarification
