### ISSUE TITLE
[1.16.x] [2.4.4] Modded Armor weight system broken on MP environment. 

### ISSUE THREAD

**Issue by Cixon** [Insane96/IguanaTweaksReborn#131]
// Usually only latest versions are supported

**Minecraft Version**:
Title.

**Mod Version:**
Title.
Elenai Dodge: v1.0.8b
Ice and Fire: v2.1.6

**Forge Version**:
36.0.42 - server and client.

**What Happened**:
Upon using the latest update that adds Elenai dodge weight reduction support, I decided to test it on a multiplayer environment so see how it would go.

Here was the experiment using [Ice and Fire mod](https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons/files/3217622) as the modded armor test dummy:

Player 1 (host, me) - Wears full set of Firedragon steel armor. Can move freely.

Player 2 (partner) - Wears full set of Firedragon steel armor. Cannot move at all.

**Addition context:** Both inventories were cleared prior to test. Only wearing the Firedragon steel armor set.
We even tested the Lightweight enchantment from Elenai Dodge on the gear to see if Player 2 could move, this didn't fix the problem.

//Please send logs even if you don't have any crash, and use Gist or Pastebin
[latest.log](https://github.com/Insane96/IguanaTweaksReborn/files/6119698/latest.log)

**Logs / Crash reports**:
N/A

//If different from default
**Config**:
[iguanatweaksreborn-common.txt](https://github.com/Insane96/IguanaTweaksReborn/files/6119700/iguanatweaksreborn-common.txt)
_(was .toml but github wouldn't let me upload it so I converted to .txt)_

**List of mods installed / modpack**:
https://drive.google.com/file/d/1ygQOymSTVVgs_FosZUk-m5ojiUkKlRhi/view?usp=sharing
Personal.

**Comment by Insane96** [comment]
Could you send an F3 screenshot for both players? Also did both players
have the same config?

**Comment by Cixon** [comment]
I can't send F3 screenshot right now as the other player is asleep.

I will say that the other player didn't have the same config as me, they had a default config file where as I shared the same one as the server.

Usually the server's config determines the settings for everyone so I didn't think that'd be the reason for this bug.

**Comment by Insane96** [comment]
Then that's a know bug. Right now the clients must have the some config as the server, otherwise you get desynced.

**Comment by Cixon** [comment]
Understandable, hopefully this is fixed soon.
In addition to this, I noticed the light-weight enchantment didn't really benefit modded armor by much or at all.

It could have been just miniscule but even making every set piece tier 3 light-weight enchanted it wasn't noticeable.

Was the tiers considered as well?
I tested with the heaviest armor set dragon steel with tier 3 light-weight but I felt just as slow without the enchant.

**Comment by Insane96** [comment]
That's because you need to set the total armor weight in the config,
otherwise the calculation only takes into account armor points and not the
worn armor.

Il Gio 11 Mar 2021, 07:54 Cixon <notifications@github.com> ha scritto:

**Comment by Cixon** [comment]
Is this the same line in the config where u have the vanilla gear setup?

**Comment by Cixon** [comment]
I'd love a link to a guide if there is one or perhaps a reference, I'm still new to this mod. XD

**Comment by Insane96** [comment]
Yes

Il Gio 11 Mar 2021, 07:59 Cixon <notifications@github.com> ha scritto:

**Comment by Insane96** [comment]
It's written in the comment

Il Gio 11 Mar 2021, 08:02 Cixon <notifications@github.com> ha scritto:

**Comment by Cixon** [comment]
I see, I'm sure I can figure it out. Thanks again!

**Comment by Cixon** [comment]
Is this correct? I tried it in conjunction with the lightweight enchantment on the modded armor and it didn't make me any faster.

"Material Weight" = ["leather,1.0", "chainmail,5.0", "golden,12.0", "iron,9.0", "betterendforge:terminite,9.0", "iceandfire:silver,11.0", "diamond,13.0", "aquaculture:neptunium,13.0", "betterendforge:crystalite,14.0", "iceandfire:dragonscale,15.0", "netherite,16.0", "iceandfire:dragonsteel,20.0", "betterendforge:aeternium,25.0"]

**Comment by Cixon** [comment]
The config saved and didn't override it so I figured I did it correctly? Not 100% sure..

**Comment by Insane96** [comment]
Check the logs, there are Warnings (or errors I don’t remember) if you didn’t add armors correctly
