### ISSUE TITLE
Make exponentially enlarging farms difficulty

### ISSUE THREAD

**Issue by Insane96** [Insane96/IguanaTweaksReborn#137]
Reduce seeds drop when harvesting crops, making it harder to exponentially enlarge farms.
Add Potato and Carrot Seeds for that purpose. 
Think what to do about pumpkins and Melons

**Comment by Mike-U5** [comment]
One possible solution for Melons/Pumpkins could be to generate "wild" melons and pumpkins that drop seeds. A bit like the wild crops that Farmer's Delight adds.
