### ISSUE TITLE
[1.16.5] The text "starvespeed: 600" displays on-screen when starving

### ISSUE THREAD

**Issue by eolinao** [Insane96/IguanaTweaksReborn#179]
* Minecraft:  1.16.5
* Forge: 36.2.0
* IguanaTweaks Reborn:  2.7.4-mc1.16.5
* InsaneLib: 1.1.2-mc1.16.5

**What Happens**:  
When starving, "the text starvespeed:600" appears above the hotbar. It disappears when not starving anymore. 

**Logs / Crash reports**:  
https://pastebin.com/UpxkttwX

**Image:**
https://i.imgur.com/JsW2p6n.png

**Config**:  
Default config

**Can be reproduced with IguanaTweaks Reborn + InsaneLib only?**:  
Yes

**Comment by Insane96** [comment]
Already fixed for next updste. Thanks

**Comment by Insane96** [comment]
Sorry, didn't mean to lock it
