### ISSUE TITLE
Encumbrance should check for backpacks content

### ISSUE THREAD

**Issue by Insane96** [Insane96/IguanaTweaksReborn#21]
I really don't know how to add support for mods. I'll try in the future

- [x] Shulker Boxes
- [ ] Wearable Backpacks
- [ ] Golden Bag of Holding from Extra Utils
- [ ] Quark Oddities' Backpack

More?

**Comment by Insane-96** [comment]
test

**Comment by cosmicdan** [comment]
I could probably do a PR for this, sometime soon. For one of those mods anyway - whichever we decide to go with

Probably also want to check the Shulker box?

**Comment by Insane96** [comment]
Shulker Box is already in

Il Sab 25 Mag 2019, 07:18 Daniel Connolly <notifications@github.com> ha
scritto:

**Comment by cosmicdan** [comment]
Yeah I saw the title was edited, no worries.

I've made a link to this issue in my project tasks so when I get to it I'll check back here before doing any work on it.
Cheers

**Comment by Insane96** [comment]
Cleaning up old issues
