### ISSUE TITLE
Game Stages/CraftTweaker Integration

### ISSUE THREAD

**Issue by imIrony** [Insane96/IguanaTweaksReborn#56]
Was wondering if it is possible to create integration for mechanics within ITR and the [Game Stages](https://minecraft.curseforge.com/projects/game-stages) mod.

Perhaps allowing encumbrance, stack sizes and block exhaustion for example to be controlled dynamically which is determined by the stage the player is currently in. This would most likely require a way to reload and reference unique configuration files through JSON for which mechanics they alter or using CraftTweaker scripting to modify values.

**Comment by Insane-96** [comment]
It's already in the plan to make Encumbrance etc as JSON, for the stages integration I'll think about it.

**Comment by Insane96** [comment]
Nothing planned right now.
