### ISSUE TITLE
Punishing tool progression xD

### ISSUE THREAD

**Issue by LokyLive** [Insane96/IguanaTweaksReborn#79]
Minecraft Version: 1.12.2

Mod Version: 
ITR : 1.4.14
Tool Progression : 1.6.6

Forge Version: 23.5.2824

What Happens:

To fix the problem with immersive craft (immcraft:rock and immcraft:stick) harvest lvl and tool effectivity (cause punishing tool is not affected from the Block/blacklist) i've tryed to use th "Tool Progression" mod but punition tool don't detect the change of hardness overwrite waila info.

**Comment by Insane-96** [comment]
> To fix the problem with immersive craft
Which problem?

**Comment by LokyLive** [comment]
i can't break "immcraft:rock" or "immcraft:stick" with empty hand with tool punition enable so i've tryed to change harvestability of the immcraft:rock/stick with "Tool progression"

**Comment by Insane96** [comment]
Closing for cleanup
