### ISSUE TITLE
Request for weight mechanic

### ISSUE THREAD

**Issue by O13SC3N3** [Insane96/IguanaTweaksReborn#80]
1.12.2 Id like to see encumberence do more then just slow a player down. Maybe beyond the 50-75% threshold makes swimming a bit more difficult? Beyond 75% sink like a rock? Game over?

**Comment by Insane-96** [comment]
It's already like this

**Comment by O13SC3N3** [comment]
Everything i've tested with being overweight almost to the point of barely moving, Your able to swim faster then able to walk. And you sink normally. I think once you hit a threshold of weight you shouldnt be able to swim at all, just sink like a rock.

**Comment by cosmicdan** [comment]
@O13SC3N3 - so are you saying it's buggy and doesn't work properly in water? And then resets to full speed once leaving the water?

**Comment by Insane96** [comment]
No further response. Closing
