### ISSUE TITLE
Crash between – Foam fix, Iguana Tweaks and Future MC

### ISSUE THREAD

**Issue by Pseudohuman93** [Insane96/IguanaTweaksReborn#83]
Hello,
There seems to be an issue with three mods.
I’m reporting to all of them so they can be aware of the issue.
Thanks, in advanced to all of them for their response.
This is the crash log:
-	https://paste.dimdev.org/puzivusugu.mccrash
The crash happens when I start Minecraft.
(You may want to talk to each other to avoid compatibility issues)

**Comment by Insane96** [comment]
Remove FoamFix

Il Dom 19 Mag 2019, 17:15 Pseudohuman93 <notifications@github.com> ha
scritto:

**Comment by Insane96** [comment]
Remove FoamFix and see if it crashes again

**Comment by XvBUSHvX** [comment]
Disabled FoamFix's Core mod features. New crash occurs, leaving FoamFix out of it.

VanillaFix identified Furturepack API, Futurepack, and IguanaTweaks Reborn as potential causes. [Report](https://paste.dimdev.org/usatuhirek.mccrash)

Futurepack is the newest of the 3 installed in the pack I am working on...

**Comment by Pseudohuman93** [comment]
I don't know what you did, but it seems to work now! Thanks!! 

Can't wait for the coral blocks!!

**Comment by Insane96** [comment]
> I don't know what you did, but it seems to work now! 

What?
