### ISSUE TITLE
Movement not slowing down at all, regardless of config

### ISSUE THREAD

**Issue by cosmicdan** [Insane96/IguanaTweaksReborn#84]
Latest 1.12.2 version, latest Forge version. All other mods removed.

Movement is not slowed down depending on block the player is walking on.

Running default config, also tried setting all the slowdown values to 100.0.

**Comment by cosmicdan** [comment]
Likely unrelated but I've also noticed that FOV lock is also not working.

If you don't have time to look into this within the next couple weeks, I could see whats up and maybe do a PR.

**Comment by Insane96** [comment]
Just tried and it works in Dev environment

**Comment by cosmicdan** [comment]
Don't know what else to tell you, so I'll explain the quickest steps I made to reproduce.

1) Added a new 1.12.2 instance to MultiMC, with Forge .2768 (same as you build the mod against)
2) Boot once to let default config generate, restarted instance after adding an entry "minecraft:sand,50" under "Custom Terrain Slowdown" config
3) Start a new Survival world game. Walking on sand or through tall grass does *not* slow me down.

Note that slower-walking-when-walking backwards *does* work, as does encumbrance from inventory items. But terrain-specific slowdown does not work.

Don't worry about the FOV thing, I was testing during sprinting which still changes FOV but the lock seems working otherwise.

**Comment by Insane96** [comment]
Try updating forge and tell me if something changes
