### ISSUE TITLE
Enhancement: Config option to disable the speed calculation for Mobs (non-player entities)

### ISSUE THREAD

**Issue by SirAron111** [Insane96/IguanaTweaksReborn#85]
Currently you can either have the speed calculation turned on or off and when it’s on you can set the speed in ticks how often this gets calculated. Would it be possible to turn this module on separately for players and mobs so I can turn of the mobs speed check? I have other mods handling mob speed and random speed paces for them. But I use the Speed setting for players to make armor with high values Wight the player down. But the extra speed calculation for mobs is really taxing on servers in my Modpack where there are around 3 times the mobs than normal.

**Comment by Insane96** [comment]
"Tick Rate Entity Update" can now be set to 0 to disable Movement Restriction for mobs.

**Comment by Insane96** [comment]
This is just a quick fix and will probably make a small config rework near in the future to make this better
