### ISSUE TITLE
Crash: Servers Crash on ticking entity.

### ISSUE THREAD

**Issue by SirAron111** [Insane96/IguanaTweaksReborn#86]
Unless the issue is a suggestion, for crashes and bugs follow the following guideline. Not following this will result in ignored and closed issue.

// Versions before 1.12 are not supported

Minecraft Version:

// Please make sure you're using the latest version before sending a report

Mod Version:
[1.12.x] IguanaTweaks Reborn 1.4.17

Forge Version:
14.23.5.2838

What Happens:
The Server Crashes directly after generating the world before anyone can even join
I will test if it has to do with the setting change of setting mob movement check to 0
Edit: even when setting the movement check on tick back to someting like 8 or 100 it still crashes

//Please send logs even if you don't have any crash, and use Pastebin or similar

Logs / Crash reports:
Here the first one with it set to 0 (how i wanted it to be) https://pastebin.com/6tWG6L9L
Here the crash with tick check for mobs set to 100 https://pastebin.com/hsKddtrK
Works fine in singlepalyer

//If needed
Config:
https://pastebin.com/WkLPdtFG

List of mods installed / modpack: 
Dimension Zero (Dev version not downloadable)

**Comment by Insane96** [comment]
It's not the Tick Check the problem. I don't know wtf happened

**Comment by Insane96** [comment]
This crash makes no sense

**Comment by SirAron111** [comment]
You say the crash makes no sense But the update seems to have fixed it. Can I ask what you did to fix it? You must be a genius if you can fix things that make no sense XD….well at least it doesn’t crash anymore on servers since the update. GJ on the fast work! Ladders are also nice now no more stuttering.

**Comment by Insane96** [comment]
Still doesn't really make too much sense but I think that by adding https://github.com/Insane96/IguanaTweaksReborn/blob/master/common/net/insane96mcp/iguanatweaks/modules/ModuleMovementRestriction.java#L460 those two methods at the end of the file, when he was calling ApplyPlayer he tried to use the two methods at the end of the file, but before the end of the file there was this method https://github.com/Insane96/IguanaTweaksReborn/blob/master/common/net/insane96mcp/iguanatweaks/modules/ModuleMovementRestriction.java#L385 that's client side only and was "scanned" and read EntityPlayerSP that exist only ClientSide
