### ISSUE TITLE
Bug: Iguana Tweaks disables all functionality for mods that change harvest speed.

### ISSUE THREAD

**Issue by SirAron111** [Insane96/IguanaTweaksReborn#87]
// Versions before 1.12 are not supported

Minecraft Version:
1.12.2

// Please make sure you're using the latest version before sending a report

Mod Version:
[1.12.x] IguanaTweaks Reborn 1.4.15 and newer I did use the latest version as well (it’s the one I noticed the bug i reduced the versions until i found the one that added this bug)

Forge Version:
14.23.5.2838

What Happens:
Iguana Tweaks Reborn 1.4.15 ---Fixed a possible compatibility with mods that mess with Breaking Speed (Tinkers' Construct was one)

This change also broke any compatibility with any mod adding skills that increase harvest speeds with shovels axes pickaxes literally anything.
Or any other mod that changes harvest speed other than the basic speed upgrade from tinkers Redstone modifier. 

This also not only affects skill mods but also normal mine craft haste seems to sometimes be affected also any bauble item that adds a mining speed or potions or other buffs… I wonder how I didnt notice that sooner until a player came to me he I upgraded x skill and it doesn’t go faster anymore what’s wrong XD.
Well I went around and tested with various mods that add skills items or buffs that increase your mining speed and other than Redstone modifier from tinkers nothing makes you faster anymore.
This is sad as I was literally using iguana tweaks to make the start hard and gave them skills to make them feel like getting better when they slowly crawled up to normal mining/tee felling/shoveling speed. All tools from all mods are affected by this

Easy combination to test this with would be.
Newest version of Iguana Tweaks Reborn and improvable skills 3 mod!

Try it out you won’t get any faster at mining or other harvesting if you increase the skills anymore. Unless you disable the hardness global config of ITR

All versions below this IT Reborn 1.4.15 seem to work fine.

**Comment by Insane96** [comment]
Could you please try out this version (you need to extract it)?

[MiningSpeedFix.zip](https://github.com/Insane96/IguanaTweaksReborn/files/3471095/MiningSpeedFix.zip)

**Comment by SirAron111** [comment]
That seems to have fixed it but also disabled the hardness x4 (even made new config for ITR) the mining speed of all things scales again now like skills and momentum mining ring etc. But the Hardness of blocks is entirely gone. I mean it’s in the config but with but on true and on false doesn’t matter still the same base speed/hardness. (Yes I did restart in-between global hardness change true/false)
