### ISSUE TITLE
Bug: Speed modifiers work again now but the hardness settings are ignored.

### ISSUE THREAD

**Issue by SirAron111** [Insane96/IguanaTweaksReborn#89]
Bug: Speed modifiers work again now but the hardness settings are ignored.

The update seems to have fixed it but also disabled the hardness x4 (even made new config for ITR) the mining speed of all things scales again now like skills and momentum mining ring etc. But the Hardness of blocks is entirely gone. I mean it’s in the config but with it on true and on false doesn’t matter still the same base speed/hardness. (Yes I did restart in-between global hardness change true/false)

Tested it with the zip filed version you send me and the released new one (which is the same anyway but i still did test just in case)

Posted this on the issue you closed but I thought it would be better in its own new one since I don’t know you if you get the notification if it’s closed.

**Comment by SirAron111** [comment]
Seems to work fine now all things work speed/hardness/tinker abilitys modifers speed rings skills etc etc great work.... now to test this stuff on a server XD

**Comment by SirAron111** [comment]
servers also wrok great Xd

**Comment by Insane96** [comment]
Yaaaay

Il Mer 7 Ago 2019, 02:23 SirAron111 <notifications@github.com> ha scritto:
