### ISSUE TITLE
You can add Block Physics effect？

### ISSUE THREAD

**Issue by Abo233** [Insane96/IguanaTweaksReborn#90]
block is like sand falling down
add a list

**Comment by Insane96** [comment]
You mean making any block fall like sand or gravel?

**Comment by Abo233** [comment]
Add a  block Physics list

Let the player decide for himself

**Comment by Insane96** [comment]
You mean add a list of blocks affected by gravity like sand and gravel?

Il Dom 18 Ago 2019, 12:27 Abo233 <notifications@github.com> ha scritto:

**Comment by Abo233** [comment]
Yes

**Comment by Insane96** [comment]
Not possible without replacing blocks with similar ones that fall. And replacing is bad.

**Comment by Abo233** [comment]
I don't know what it means, can you tell me clearly?

**Comment by Insane96** [comment]
Take _x_ block and replace it with the same block but that can fall

**Comment by Abo233** [comment]
Can I update？

**Comment by Insane96** [comment]
What?

**Comment by Abo233** [comment]
just came back today, I didn’t see your post very much

**Comment by Insane96** [comment]
What do you mean?

Il Dom 18 Ago 2019, 18:16 Abo233 <notifications@github.com> ha scritto:

**Comment by Abo233** [comment]
Block Physics   This module is available on curseforge. I saw that it only has version 1.8, so I want to ask the landlord to update it to your module.

**Comment by Insane96** [comment]
It used some tricky things to make blocks fall

**Comment by Abo233** [comment]
I may describe it incorrectly

**Comment by Insane96** [comment]
Please use something else to translate, it's pretty confusing

**Comment by Abo233** [comment]
Enviro Mine mod also has block physics Effect

You can also go and see

**Comment by Abo233** [comment]
Good night

**Comment by Insane96** [comment]
Is it possible to do it but takes too much time and it's not worth the
effort.
