### ISSUE TITLE
Can you add a setting to modify the attack distance？

### ISSUE THREAD

**Issue by Abo233** [Insane96/IguanaTweaksReborn#91]
I think the player's hands are too long
It's too easy.

**Comment by Abo233** [comment]
Can you add this setting？

**Comment by Abo233** [comment]
The hands are too long. It's not difficult to fight.

**Comment by Insane96** [comment]
There's no way to change attack distance without changing block break distance

**Comment by Abo233** [comment]
By modifying the player attribute reach

**Comment by Insane96** [comment]
> Found no way for now to change attack distance without changing block break distance

**Comment by Insane96** [comment]
Maybe I can hook on AttackEvent to prevent the attack if it's to far away ...

**Comment by Insane96** [comment]
So, I can do this with LivingAttackEvent by canceling the event if the player is too far away. The problem is the crossair, it shows the attack can be made even when too far away. I could rewrite the render of the Crossair but I don't know how much of pain is. Will definitely try.

**Comment by Abo233** [comment]
Hard work for you

**Comment by Insane96** [comment]
This will be definitely possible in vanilla as new combat update, but right now is too much pain.
