### ISSUE TITLE
You can add a list of dimension block hardness?

### ISSUE THREAD

**Issue by Abo233** [Insane96/IguanaTweaksReborn#92]
I want to change other dimensions of block hardness

For example the OverworldMultiplier = 4.0
                          The netherMultiplier = 8.0

**Comment by Insane96** [comment]
You need this only for the global multiplier?

**Comment by Abo233** [comment]
No, I still have a lot, I just plan to increase the difficulty of other dimensions

**Comment by Abo233** [comment]
I want to configure by adding a dimension id

**Comment by Abo233** [comment]
I know all dimension ids

**Comment by Abo233** [comment]
Just missing your list
