### ISSUE TITLE
Hardcore farming

### ISSUE THREAD

**Issue by Undermmon** [Insane96/IguanaTweaksReborn#93]
Add options to: 
- Change crop growing speed
- If crops need water to grow
- If crops only can grow with sunlight, additionally a whitelist of light sources which can grow the crop.

**Comment by Insane96** [comment]
What do you mean by the second one?
And also the third one is partially possible. The sunlight thing is possible, but not the light sources one without having heavy performace hits

**Comment by Insane96** [comment]
Done in the latest 4 commits
https://github.com/Insane96/IguanaTweaksReborn/commit/8f18657922610954281f567f1594001fbc671028
https://github.com/Insane96/IguanaTweaksReborn/commit/f16ee93c90459df2dd9eaf3247e60e2d9336db6c
https://github.com/Insane96/IguanaTweaksReborn/commit/7e87d958232e6694707a9ff09200c99c8fa1d417
https://github.com/Insane96/IguanaTweaksReborn/commit/3184096087e440a8d0b05924184d95b5076c0594
