### ISSUE TITLE
Sleep Overhaul

### ISSUE THREAD

**Issue by Candy-Poppi** [Insane96/IguanaTweaksReborn#98]
Hey Bonjour!

I don't know your plan about this mod, but, i got a little suggestion for a feature with beds!

So, when the player will sleep, his hunger will decrease dramatically, because it's logical (each morning, i'm really hungry, a bit much...).
Tiredness system, all action (run, jump, walk, mine, dig, swim...) increase our tiredness, more tired he goes, more slowly he'll. If he's too tired, he can pass out, and another day begin. 

I hope i'm the first with this idea, and you like it ;)

NB : Don't blame me, i'm not english, so yeah... i probably made somes mistakes.

**Comment by Insane96** [comment]
For the tiredness you're a bit late #30 
As for the hunger in the morning I like it

**Comment by Candy-Poppi** [comment]
Aaaaah! Awesome, it's not implemented yet, true?

Thanks for your answer, you did a great job!

**Comment by Insane96** [comment]
The hunger (also Slowness and Regeneration effects) are applied on wake up as 2.1.0
