### ISSUE TITLE
Can you add a new buff?

### ISSUE THREAD

**Issue by Abo233** [Insane96/IguanaTweaksReborn#99]
1.Seriously buff：HP regeneration by half or more(Configurable percentage)

instructions
： （1）When a player is below twenty-five percent health, get this effect（Configurable percentage）
      
      （2）HP is higher than fifty percent, the buff disappear automatically（Configurable percentage）

**Comment by Insane96** [comment]
What's the purpose of this?

Il Lun 10 Feb 2020, 05:46 Abo233 <notifications@github.com> ha scritto:

**Comment by Abo233** [comment]
To improve the game difficulty
 
You can consider to make BUFF and percentage allows players to configure

**Comment by Abo233** [comment]
When the player blood loss to a certain extent, can trigger a BUFF

**Comment by Abo233** [comment]
就像这个模组一样[First Aid]

**Comment by Abo233** [comment]
This is a big change
Suggest to add a new module[combat]

**Comment by Insane96** [comment]
Wait you mean reducing health regen by half or increasing it?

Il Mar 11 Feb 2020, 05:48 Abo233 <notifications@github.com> ha scritto:

**Comment by Abo233** [comment]
HP Regen speed halved

**Comment by Insane96** [comment]
Sadly health and hunger changes require AppleCore that can change ... well ... hunger and health. Some changes are planned (like disable vanilla health regen and make one by myself) check #102
